# 🔟❎ 'run' Reducer settings

# This configuration defines the settings for use by the Reducer app.
# When 'reducerOptimize' is enabled, the reducer also encodes emitted
# events for volume reduction (formerly the separate Edge Optimizer app).
# To learn more see https://doc.log10x.com/apps/reducer

tenx: run

# ============================= App Settings ==================================

runtimeAttributes:
  - app:reducer
  - env:edge

include:
  - apps/shared
  - run/aggregate/regulate # https://doc.log10x.com/run/aggregate/#regulate
