# 🔟❎ 'compile' ANTLR symbol scanner settings

# The 10x 'compile' pipeline leverages the polyglot ANTLR (http://www.antlr.org)
# library to parse and extract symbol values (e.g., class names, code constants,..)
# and the context in which they appear in their source files in various languages.

# Parsing source code files for a given language can be done by:

#   - compiling a .g4 grammar file (see https://github.com/antlr/grammars-v4)
#     using the ANTLR tool into a parser .class file, loaded by the 10x 'compile' pipeline. 

#   - Passing a .g4 grammar file directly to the 10x 'compile' pipeline, 
#     assuming the target grammar does not require any language-specific code extensions.

# The 10x ANTLR scanner uses pre-compiled and interpreted ANTLR parsers
# to read the source file's contents and iterate its AST tree. The scanner 
# uses the 'rules' list defined below for each language to control
# which symbols to extract from the AST tree and their context within the code
# (e.g. class name, constant, enum,..).

# This approach enables the 10x 'compile' pipeline to create a 10x symbol files
# from source code files written in virtually any programming language, 
# and any text file that matches a target ANTLR grammar.

# To learn more about using ANTLR, see: https://tomassetti.me/antlr-mega-tutorial

# 'langs' defines the ANTLR grammars the 10x 'compile' pipeline can use.
langs: 
  - $?antlrLangs

# 'rules' defines which nodes to select from an ANTLR AST tree based on specified rule selectors
rules:
  - $?antlrRule
  
# 'logMethods' defines method names (e.g., 'error', 'warn') as 'logging'
#  within the ANTLR AST tree. Arguments to logging method calls within the AST tree 
#  receive a higher priority when selecting the origin of an TenXTemplate symbol sequence. 

#  For example, a call to: 'logger.error("server fail", e);' in 'log.java' implies that the
#  string constant passed to the method has a higher likelihood of appearing in a log file than
#  if it were defined in the following source line: 'button.caption =  "server fail;" in 'gui.java'
#  As such, when selecting the source origin for a log event containing the expression "server fail",
#  'log.java' will be selected ahead of 'gui.java'. To learn more about template symbols, 
#  see: https://doc.log10x.com/run/transform/symbol
logMethods: +include compile/modules/scanner/logMethods/settings.yaml
# 'parseUnitTimeout' defines the timeout interval for parsing and scanning
#  a single source/binary input file before it is aborted and marked with a timeout error 
parseUnitTimeout: $?antlrParseUnitTimeout=60s