#
# 🔟❎ 'run' symbol origin selector settings

# 10x JavaScript functions provide the ability to filter/aggregate TenXObjects 
# based on where their  source code /binary executable origin
# to identify the application/infrastructure log events that 
# consume the most network, storage, and analytics licensing resources.

# ----------------------------- Symbol Selector -------------------------------

# 'maxSymbolOrigins' controls the number of source/binary origins to list
#  per symbol token sequence. As a series of tokens within a given 
#  template (e.g., 'ERROR', 'could not connect to "{}') may appear
#  in multiple source/binary files within the pipeline's provided symbol files.
#  The sorting algorithm configured below is used to select the 'maxSymbolOrigins'
#  topmost entries to list.
maxOrigins: $?symbolMaxOrigins=64

# ----------------------------- Symbol Contexts -------------------------------

# Each symbol extracted from a source/binary file is stored in a symbol unit file
# (*.json), which marks both its origin file (e.g., 'foo.js')
# and the context in which it appears in the file  (e.g., class name, constant).

# The information is known as 'symbol context' and provides the ability for
# user-defined 10x scripts executed by the 'run' pipeline to categorize and
# aggregate TenXObjects based on their structure/schema, similar to reflection
# functions allowing developers to process objects based on their structure/origin.

# To learn more see https://doc.log10x.com/compile/scan/

# Below are the possible contexts in which a string may appear in its origin file:

# - 'enum': literal value of a source code enum.
#   For example, 'OK','FAIL','RETRY' literals in: 'enum Status {OK,FAIL,RETRY}'

# - 'logger_method_invoke': a constant passed directly to a logger. For example:

#     function hostError(host) {
#       // the "error connecting" symbol is passed directly to the logger
#       console.error("error connecting", host));
#     }

#     Logger method names are defined in 'compile/config/logMethods/config.yaml'.

# - 'logging_method_invoke': constant arg within a logging method. For example:

#      function hostError(host) {
#        // The "error connecting" symbol is passed as an indirect arg to the logger
#        var msg = fmtError("error connecting", host);
#        console.error(msg);
#      }

# - 'logging_method_var_assign': constant value within a logging method. For example:

#      function hostError(host) {
#        // The "error connecting" symbol is passed as an indirect variable to the logger
#        var msg = "error connecting: " + host;
#        console.error(msg);
#      }

# - 'package': the name of a code package/namespace (e.g. 'com.acme.util')

# - 'class': name of a class definition. For example:
#     'BlockManager' in 'class BlockManager {...}'

# - 'interface': name of a code interface declaration. For example
#     'IBlockManager' in: 'interface IBlockManager {...}'

# - 'var_assign': string constant assigned to a variable. For example, 'radius' in:

#     function radStr(c) {
#       var str = "radius:" + c / 6.28;
#       return str
#     };

# - 'method_invoke': string constant passed as a method arg. For example, 'items' in:

#     function lenStr(arr) {
#       return arr.length.toString().concat(" items");
#     };

# - 'method_decl': name of a source code method/function
#    For example: 'hostError' in: 'function hostError(host) {')

# - 'executable_sym': text symbol compiled into binary executable file/library
#    Learn more about executable symbol scanning at https://doc.log10x.com/compile/scanner/executable

# - 'plain_text_sym': text symbol within a plain text file (e.g., .xml, .json)
#    To learn more about text symbol scanning, see: https://doc.log10x.com/compile/scanner/text

# - 'annotation_invoke': constant within a code annotation. For example, 'personAge' in:
#     @JsonElement(key = "personAge")
#     public String age;


# 'symbolSequenceReserved' defines a list of terms to ignore when searching
#  for the symbol tokens that constitute an TenXTemplate's 'message' portion.
#  For example, for an event whose text contains: 'connect success = true',
#  the value 'true' will not be considered a part of the event's message,
#  as the 'true' value is likely the result of a variable boolean state.
#  To learn more see [TenXObject.symbolSequence](https://doc.log10x.com/api/js/#TenXObject+symbolSequence).  
sequenceReserved:
  - |
    $?symbolSequenceReserved=
    - "null"
    - "nil"
    - "true"
    - "false"
    - "to"
    - "the"
    - "a"

# ----------------------------- Debug Settings --------------------------------

# 'debugSymbols' outputs information on selecting
#  symbol origin/context for a sequence of symbol tokens within an TenXTemplate.
#  For example, set 'Could not connect to' to log how a source code/binary origin 
#  is selected from the pipeline's symbol files.
# Specify '*' to print information for all symbols.
debugSymbols:
  - $?symbolDebugSymbols

# 'debugOrigins' specifies a list of source/binary files (e.g., 'foo.js') for printing debug information.
#  For example, specify 'foo.js' to debug why this file is/not selected at the origin value
#  of a target TenXTemplate symbol sequence .
# Specify '*' to print information for all origins.
debugOrigins:
  - $?symbolDebugOrigins

# 'loggerName' specifies the log4j logger name for 'debugOrigins' and 'debugSymbols'.
#  Default value: 'consoleOut' (defined in the 10x Engine's log4j2.yaml).
loggerName: $?symbolDebugLoggerName=consoleOut
