#
# 🔟❎ 'compile' invoker app

app:

  name: compiler

  title: Compiler

  description: generate symbol libraries to enable structured event processing at runtime

  # 'doc' specifies the markdown doc content, only required when generating docs.
  doc: +include $=TenXEnv.get("docGenerate") ? "apps/compiler/doc.md":""
  
    # 'configFolders' specifies folders containing default configuration files for this module
  configFolders:

    compiler: apps/compiler

    pull: compile/pull
    pull+GitHub: compile/pull/github
    pull+Docker: compile/pull/docker
    pull+Helm: compile/pull/helm
    pull+Artifactory: compile/pull/artifactory

    scan: compile/scanners

    link: compile/link

    push: compile/push

  advancedConfigFolders:
    
    bootstrap: compile/bootstrap
    github Sync: gitops

    scan: compile/scanners/advanced

    scan+antlr: compile/scanners/antlr
    scan+pythonAST: compile/scanners/pythonAST
    scan+executable: compile/scanners/executable
    scan+text: compile/scanners/text
    scan+patterns: compile/scanners/pattern
    scan+archive: compile/scanners/archive
    scan+logMethods: compile/scanners/logMethods


