#
# 🔟❎ 'compile' scan and link settings

#  The 10x 'compile' pipeline scans input source code/binary files to capture symbol values into symbol unit files.  
#  Once scanning of supplied input paths completes, the pipeline combines output symbol files 
#  into a single symbol library file.

#  The 10x 'run' pipeline uses symbol libraries to transform input log/trace events into well defined, class-based TenXObjects.

# 'inputPaths' provides a list of file/folder locations containing source/binary input
#  files to scan for symbol values (e.g., class names, string constants, enums,..)
inputPaths:
  - $outputSymbolFolder
  - $inputPaths

# 'token' controls how to break string values found in input source/binary files into individual tokens
token: 
  # 'tokenDelims' defines which characters break a string of event characters into tokens to 
  # classify as symbols or variables.
  tokenDelims: $?tokenDelims=<>|. ][:-+/*=\\,{}_();'\"$\t\n@

  # 'fileExtStringFormats' controls which characters identify the start of a format specifier (https://en.wikipedia.org/wiki/Printf#Format_specifier). 
  fileExtStringFormats: 
    - $?fileExtStringFormats

# 'symbolScan' sets the scanner modules for parsing and generating ASTs for input files.
symbolScan: +include compile/modules/scanner/settings.yaml

# 'symbolProcessing' controls symbol unit information generated from scanning
#  source/binary input files is stored.
symbolProcessing: 

  # 'threadPoolSize'controls the maximum number of threads to concurrently
  #  process input source/binary files. If the value is between 0 and 1, the number calculates 
  #  a percentage of available cores (e.g., 0.5 = use up to 50% of available cores).
  #  If the value is >= 1, the value sets a fixed number of threads (e.g., 10 = 10 threads).
  #  If the value is 1, allocate a single thread to process input files.
  scanThreadPoolSize: $=TenXMath.parseDouble(TenXEnv.get("scanThreadPoolSize"), 0.5)

  # 'scanUnitTimeout' sets the timeout interval when scanning a source/binary input
  #  file before dropping it. Set to null to ignore.
  scanUnitTimeout: $?scanUnitTimeout=30s

  # 'scanOperationTimeout' sets the timeout interval for the entire scanning operation
  #  before terminating it. Set to null to ignore.
  scanOperationTimeout: $?scanOperationTimeout=10m

  # 'maxSymbolUnitSectionSize' controls the maximum number of symbol tokens to store in a symbol unit before splitting it. 
  #  This option provides support for parsing source code/binary input files that may have thousands of text symbols to avoid creating
  #  large individual symbol unit files.        
  maxSymbolUnitSectionSize: $?maxSymbolUnitSectionSize=1000

  # 'scanForce' controls whether to reuse matching symbol files within 'inputPaths'.
  # This option is primarily useful when debugging a new scanner module configuration (e.g., ANTLR grammar) 
  # in conjunction with the [scanner debugging](https://doc.log10x.com/compile/scan) options.
  scanForce: $?scanForce=false

# 'symbolIndex' controls how output 10x symbol units files (*.json)
#  are indexed for fast retrieval of symbol information by the 10x 'run' pipeline
symbolIndex: 
  # 'maxSymbolUnitsPerToken' controls the maximum number of symbol units to load from the 
  #  pipeline's symbol library when searching for the origin of a specific TenXTemplate symbol. 
  maxSymbolUnitsPerToken: $?maxSymbolUnitsPerToken=128

# 'outputSymbolLibraryFile' sets the 'compile' output symbol library file.
#  If 'outputSymbolFolder' is specified, link symbol unit files from 'outputSymbolFolder' into 'outputSymbolLibraryFile'.
outputSymbolLibraryFile: $?outputSymbolLibraryFile

# 'outputSymbolFolder' sets the root folder into which the 'compile' pipeline will
#  emit symbol unit files in a structure that mirrors 'inputPaths'
outputSymbolFolder: $?outputSymbolFolder

# 'unitsToScanPerBatch' controls the number of source/binary input files a scan subprocess will scan.
#  If this value exceeds zero, the 'compile' pipeline will launch a subprocess to scan N input files. 
#  Spawning a sub-process provides isolation for parsing and interpreting input files
#  that have complex AST structures that might otherwise cause the process to timeout or run out of memory.
#  This value is only used if 'scanInProcess' is false
unitsToScanPerBatch: $?unitsToScanPerBatch=100

# 'launchPipelineOptions' controls the startup and argument passed to a spawned
#  sub-process if 'unitsToScanPerBatch > 0
launchPipelineOptions: +include units/scan/subprocess/settings.yaml

# 'symbolTypes' controls the types of symbols collected from input source/binary files.
#  Each token read from an input file is potentially assigned a context
#  specific the logic of the parser processing the file. Possible values:
#   - package: code package or namespace (e.g. 'com.acme.util')
#   - class:   code class or interface (e.g., 'AcmeManager')
#   - method:  code method or function name (e.g., 'foo')
#   - enum:    code enumeration (e.g., 'severity: error, warn, debug')
#   - log:     string constant passed to a logging method (e.g., 'log.error("could not connect to %s",..');
#   - const:   string constant assigned into a variable or method (e.g. 'caption = "hello!"')
#   - text:    string value, usually read from a config file (e.g., JSON/XML/YAML field name)
#   - exec:    string value extracted from a binary executable input file, usually via the 'strings' os command
symbolTypes:
  - $?symbolTypes=[package,class,enum,log,text,exec]

# 'symbolFileNameFilters' specifies regex patterns to exclude symbol files (e.g., unit tests) from output symbol library
symbolFileNameFilters:
  - $?symbolFileNameFilters

# 'symbolFolderFilters' specifies patterns to exclude symbol files by folder from output symbol library.
#  Plain name (e.g., "test") matches files whose direct parent folder has this name.
#  Regex (e.g., "[/\\]vendor[/\\][a-z]+\.[a-z]") matches anywhere in full path.
symbolFolderFilters:  
  - $?symbolFolderFilters

# 'writeMessages' controls whether to emit warn/error messages gathered for output symbol unit files
#  into 'outputSymbolLibraryFile'. If an 'outputSymbolFolder' has been defined,
#  will store messages in output symbol units contained  but will not write
#  them to 'outputSymbolLibraryFile' to produce a smaller symbol library file.
writeMessages: $=!envGet("outputSymbolFolder")

# 'maxSymbolUnitFileSize' controls the maximum file size 'outputFile' can be before
#  it is split into numbered output files (e.g., <output-file1>, <output-file2>,..)
#  Splitting is done to ensure 'outputFile' is a GitHub committable artifact
maxSymbolUnitFileSize: $?maxSymbolUnitFileSize=40MB

# The settings below are used internally by the 'compile' pipeline when spawning sub-processes,
# and should generally not be passed directly to a 10x 'compile' pipeline process.

# 'scanInProcess' controls whether this process should spawn sub-processes to
#  parse the contents of source/binary input files or perform the scan directly.
#  If true, scanning of source inputs (e.g., source code files) will be done
#  within the current 10x process. If false, spawns subprocesses to parse input files and write symbol unit files (*.json).
#  This provides a level of isolation from the scanning and allows for termination
#  of the scanning process after a designated timeout and release of any allocated resources.
scanInProcess: $?scanInProcess

# 'printOutput' controls whether this process should print the results of
#  parsing the contents of source/binary input files to its stdout
#  This information is read by its spawning 10x process when 'scanInProcess' is set.
printOutput: $?printOutput
