# yaml-language-server: $schema=schema.json

# 🔟❎ 'run' Object storage configuration

# This configuration defines the available object storage platforms (e.g., AWS S3, Azure Blobs,
# GCP storage) to index and query for matching events to transform into TenXObjects.

# Accessor classes implement the 'com.log10x.ext.cloud.index.interfaces.ObjectStorageIndexAccessor' to enable
# modules to populate the index and query target input objects (e.g., log files)
# residing within an underlying object storage. 

# Set the 10x pipeline to 'run'
tenx: run


# =========================== Object Storage Options ==========================

# 'objectStorageClassName' identifies the fully qualified Java class name 
#  implementing the 'com.log10x.ext.cloud.index.interfaces.ObjectStorageIndexAccessor' interface
#  to access an underlying Object storage (e.g., AWS S3) and 10x 'run' REST endpoint.
#  The class name is preceded by a user-friendly alias in the form of: <alias>:<class>
#  referenced within configurations of queries to the target index.
#
#  The 'Local:com.log10x.ext.cloud.index.access.LocalIndexAccess' can be used when interacting
#  with the local file system for POC/testing.
objectStorageClassName:
  - AWS:com.log10x.ext.cloud.index.access.AWSIndexAccess
  - Local:com.log10x.ext.cloud.index.access.LocalIndexAccess
