# Fluentd 10x 'report' configuration
#
# This Fluentd configuration adds an 'exec-filter' plugin to the
# forwarder pipeline that launches and writes events to an 10x sub-process.

<label @TENX>
	<match **>
		# Add a Fluentd 'exec-filter' plugin to spawn a 10x sub-process
		# and set the TENX_RUN_ARGS variable to the 'report' configuration
		#
		@include "#{(ENV['TENX_RUN_ARGS']='@run/input/forwarder/fluentd/report/config.yaml @apps/edge/reporter') && 'auxiliary/tenx-exec-filter.conf'}"
		
		# This 10x pipeline configuration emits information
		# about the 10x pipeline initialization, useful for verifying the configuration
		<parse>
			@type none
		</parse>

		tag tenx-stdout

		@label @TENX-STDOUT
	</match>
</label>

<label @TENX-STDOUT>
	<match **>
		@type stdout
	</match>
</label>
