# Fluentd 'regulate' configuration over Unix domain socket
#
# This configuration utilizes the Fluentd 'exec-filter' plugin to launch
# and write events into a 10x sub-process for filtering and sampling. 
# Fluentd reads processed events from the 10x process via a Unix domain socket.
#
# To use, include this file in your Fluentd config via an '@include' directive
# and add '@label @TENX' to target input(s) to connect to the 10x process.
#
# Events read back from the 10x pipeline are returned to their proper place in
# of the main Fluentd conf because the 'forward' protocol used by the Unix input
# plugin retains the event's original tag.
#

# This both loads up the Unix based 'exec_filter' config and sets the TENX_RUN_ARGS variable
# to the 'regulate' configuration
#
@include "#{(ENV['TENX_RUN_ARGS']='@run/input/forwarder/fluentd/regulate/config.yaml @apps/edge/regulator') && 'auxiliary/tenx-unix-exec-filter.conf'}"

# Setup the return source for the regulated events coming back from the 10x pipeline
#
@include auxiliary/tenx-unix-source.conf

<label @TENX-PHASE-2>
	# Return regulated events to the main Fluentd pipeline
	#
	@include auxiliary/tenx-return-events-to-main.conf
</label>
