# Fluentd 'regulate' configuration over stdin
#
# This configuration utilizes the Fluentd 'exec-filter' plugin to launch
# and write events into a 10x sub-process for filtering and sampling. 
# Fluentd reads processed events from the 10x process via its stdout pipe.
#
# To use, include this file in your Fluentd config via an '@include' directive
# and add '@label @TENX' to target input(s) to connect to the 10x process.
#
# Events read from the 10x pipeline can be either:
#   1. Returned to their original place via '@label @ROOT' (default)
#      See: 'https://docs.fluentd.org/configuration/config-file#root-label'
#   2. Returned to a new processing label via '@label @TENX-PROCESSED'
#      This option is offered as the '@label @ROOT' option is only available
#      starting Fluentd v1.14.0, or where more granular control is required.

# This both loads up the stdio based 'exec_filter' config and sets the TENX_RUN_ARGS variable
# to the 'regulate' configuration
#
@include "#{(ENV['TENX_RUN_ARGS']='@run/input/forwarder/fluentd/regulate/config.yaml @apps/reducer') && 'auxiliary/tenx-stdio-exec-filter.conf'}"

<label @TENX-PHASE-2>
	# Handle parsing of the regulated events coming back from the 10x pipeline
	#
	@include auxiliary/tenx-stdio-parse.conf

	# Return regulated events to their original place in the Fluentd pipeline
	#
	@include auxiliary/tenx-return-events-to-main.conf
</label>
