# 🔟❎ 'run' Sub-Query application general settings

# This configuration defines general settings for use by the Sub-Query operation of the Streamer app.
# To learn more see https://doc.log10x.com/apps/streamer/#query

# ============================ Bootstrap Runtime ==============================

tenx: run    # https://doc.log10x.com/run/bootstrap

# ======================== Application Dependencies ===========================

runtimeAttributes:
  - app:streamer
  - sub_app:sub-query
  - env:cloud

include:
  - apps/shared
  - run/modules/input/objectStorage/input  # https://doc.log10x.com/run/input/objectStorage/input
  - run/modules/input/objectStorage/query  # https://doc.log10x.com/run/input/objectStorage/query

  # Allows setting of 'enrichmentFields'
  - run/modules/initialize/module.yaml

override:
  # In the query sub app the only events are our queries, which shouldn't hold up the sequencer
  - key: groupFlushTimeout
    value: $=parseDuration("200ms")
