# 🔟❎ 'compile' Scalameta symbol scanner settings

# The 'scala' parser scanner utilizes the https://scalameta.org library to
# natively parse the contents of .scala files. 

# 'logMethods' defines method names (e.g., 'error', 'warn') to mark as 'logging' methods
#  within the ANTLR AST tree. Arguments to logging methods within the AST tree 
#  receive a higher priority when selecting the template symbols of an TenXObject within a 'run' pipeline. 

#  For example, a call to: 'logger.error("server fail", e);' in 'log.java' implies that the
#  string constant passed to the method has a higher likelihood of appearing in a log file than
#  if it were defined in the following source line: 'button.caption =  "server fail;" in 'gui.java'
#  As such, when selecting the source origin for a log event containing the expression "server fail",
#  'log.java' will be selected ahead of 'gui.java'. To learn more about template symbols, 
#  see https://doc.log10x.com/run/transform/symbol
logMethods: +include compile/modules/scanner/logMethods/settings.yaml
