#
# 🔟❎ 'run' policy app

app:

  name: policy

  title: Regulator Policy

  description: generate Edge regulator event rate lookup table

  # 'doc' specifies the markdown doc content, only required when generating docs.
  doc: +include $=TenXEnv.get("docGenerate") ? "apps/edge/policy/doc.md":""

    # 'configFolders' specifies folders containing default configuration files for this module
  configFolders:

    main Config: apps/edge/policy
    
    policy Input: run/regulate/policy
    
  advancedConfigFolders:

    bootstrap: run/bootstrap
    symbols: run/symbol
    template: run/template

    transform+timestamp: run/transform/timestamp
    transform+fieldParser: run/transform/fields
    transform+origin: run/transform/symbol
    transform+group: run/transform/group
    transform+parallelize: run/transform/parallelize

