# 🔟❎ Policy app settings

# This configuration defines the settings for use by the Edge Reporter policy app.
# To learn more see https://doc.log10x.com/run/regulate/policy
tenx: run                   

# ======================== Application Dependencies ===========================

runtimeAttributes:
  - app:policy
  - env:cloud

include:
  - apps/shared
