#
# 🔟❎ 'doc' pipeline

# 'spec' defines the name, description, and structure of an 10x pipeline. 
#  Pipelines are configurable using .json/.yaml files, shell variables, and command line argument arguments. 
pipeline:

  # 'name' sets a logical name to identify and launch the pipeline. (e.g., '> tenx doc') 
  name: doc

  # 'title' specifies a user-friendly title
  title: doc

  # 'description' sets a user-friendly description for the pipeline.
  #  This text will appear when invoking the 10x Engine to list available commands (e.g.,'> tenx -help')
  description: Generate pipeline documentation
    
  # 'doc' specifies the markdown doc content, only required when generating docs.
  doc: '+include $=TenXEnv.get("docGenerate") ? "doc/doc.md":""'

  # 'options' define the list of launch arguments pipeline units can receive 
  #  via configuration files and command line arguments. These arguments include symbol file locations,
  #  inputs, aggregators, outputs, and more.
  options: +include units/units.yaml
 
# 'units' specify how to apply input launch arguments to pipeline instances.
units: +include settings.yaml
