# 🔟❎ 'run' rate regulator settings

# Set the 10x pipeline to 'run'
tenx: run

# apply the 'rateRegulator' function to all outputs if limit is set
groupFilters: '$=yield TenXEnv.get("rateRegulatorLookupFile") ? "shouldRetainEventWithLookup()" : "shouldRetainEventWithoutLookup()"'
