# 🔟❎ 'run' rate reducer settings

# Set the 10x pipeline to 'run'
tenx: run

# apply the 'rateReducer' function to all outputs if limit is set
groupFilters: '$=yield TenXEnv.get("rateReducerLookupFile") ? "shouldRetainEventWithLookup()" : "shouldRetainEventWithoutLookup()"'
