# 🔟❎ 'run' Edge Regulator settings

# This configuration defines the settings for use by the Edge Regulator app.
# To learn more see https://doc.log10x.com/apps/edge/regulator

tenx: run

# ============================= App Settings ==================================

runtimeAttributes:
  - app:regulator
  - env:edge

include:
  - apps/shared      
  - run/aggregate/regulate # https://doc.log10x.com/run/aggregate/#regulate
