#
# 🔟❎ 'run' applications

app:

  name: application

  title: Application

  description: Launch 10x applications to report, regulate and optimize log/trace events in edge and cloud environments. 

  # 'allowMultiple' is disabled for this module. Pipeline command line arguments and configuration files
  #  can specify a single value at max for each option defined below.
  allowMultiple: false

  moduleSort: []

  # 'doc' specifies the markdown doc content, only required when generating docs.
  doc: +include $=TenXEnv.get("docGenerate") ? "apps/doc.md":""
