# 🔟❎ 'run' Indexer application settings

# This configuration defines general for use by the Index operation of the Streamer app.
# To learn more see https://doc.log10x.com/apps/streamer/#index

# ============================ Bootstrap Runtime ==============================

tenx: run    # https://doc.log10x.com/run/bootstrap

# ======================== Application Dependencies ===========================

runtimeAttributes:
  - app:streamer
  - sub_app:index
  - env:cloud

include:
  - apps/shared
  - run/modules/input/objectStorage/input  # https://doc.log10x.com/run/input/objectStorage/input
  - run/modules/input/objectStorage/index  # https://doc.log10x.com/run/input/objectStorage/index

  - run/aggregate/index # https://doc.log10x.com/run/aggregate/#index

enrichmentFields:
  - index_app=TenXEnv.get("indexWriteTarget")
  - index_file=TenXEnv.get("indexReadObject")
