# 10x Fluent Bit Forward protocol configuration (Windows)

# Modify 'forwardPort' to set the port of the Forward input through which the
# 10x subprocess writes tenxObjects to Fluent Bit using the native Fluentd 'forward' protocol
#
@SET forwardPort=24224

# The 10x subprocess launched by the 'Lua' filter writes tenxObjects
# back into Fluent Bit pipeline via TCP using the native
# Fluent 'forward' protocol: https://docs.fluentbit.io/manual/pipeline/outputs/forward
#
[INPUT]
    name forward
    port ${forwardPort}
