# 10x Fluent Bit TCP configuration

# modifiy 'socketPort' to set the port of the TCP socket through which
# the 10x subprocess sends encoded tenxObjects to Fluent Bit
#
@SET socketPort=5170

# restores proper tags for tenxObjects, or sets correct one for tenxTemplates
#
[FILTER]
    Name          rewrite_tag
    Match         tenx-pipeline
    Rule          $tag ^.+$ $tag false
    Emitter_Name  re_emitted

# Read encoded tenxObjects from the 10x subprocess launched by the 'Lua' filter into Fluent Bit via a TCP socket
#
[INPUT]
    name TCP
    port ${socketPort}
    tag  tenx-pipeline
