# 10x Fluent Bit Unix domain socket configuration

# Modifiy 'forwardAddress' to set the location of the Unix domain socket through which the
# 10x subprocess writes tenxObjects to Fluent Bit
#
@SET forwardAddress=/tmp/tenx_fluentbit.sock

# The 10x subprocess launched by the 'Lua' filter writes tenxObjects 
# back into Fluent Bit pipeline via a Unix domain socket pipe using the native
# Fluent 'forward' protocol: https://docs.fluentbit.io/manual/pipeline/outputs/forward
#
[INPUT]
    name forward
    unix_path ${forwardAddress}
    unix_perm 777
