# 10x 'regulate' Fluent Bit Lua script configuration

# This file is designed to be included in your Fluent Bit '.conf' file
# using the @INCLUDE <path-to-tenx.conf> macro

# NOTE - this file needs to be accompanied by either 'tenx-unix.conf' or
# 'tenx-tcp.conf' to set up the return pipe from 10x back to Fluent Bit
#
# Use 'tenx-unix.conf' for unix based OSs, and 'tenx-tcp.conf' for Windows

# script path
# -----------
# modifiy 'tenx_lua' to set the location of tenx.lua script loaded by Fluent Bit
# to launch and write events into an 10x subprocess
#
@SET tenx_lua=pipelines/run/modules/input/forwarder/fluentbit/conf/lua/tenx-regulate.lua

[FILTER]
    Name Lua
    Match *
    script ${TENX_MODULES}/${tenx_lua}
    call tenx_process
