# This Fluentd helper configuration redirects 10x processed
# events back to the root of the main Fluentd pipeline.
#
# This is supported only for Fluent D 1.14.0 or newer.
#
# When using an older version of Fluentd, it's required to send the events
# back to a manually created label.
#
<label @TENX-PROCESSED>
	<match **>
		# Insert the resulting events back to the main Fluentd pipeline,
		# for processing according to the original directives in that config.
		#
		@type relabel
		@label @ROOT
	</match>
</label>
