# This Fluentd configuration is used internally by the stdout/unix-socket
# backed 'optimize'.

# For the 'optimize' module, route 10x Templates to their matching Splunk/Elastic
# output. To learn more see: '/run/config/forwarder/fluentd/optimize/readme.md'
<match tenx-template>
	# Send 10x templates to be handled separately from main events.
	#
	@type relabel
	@label @TENX-TEMPLATE
</match>
