# This Fluentd configuration is used internally by the stdio-backed
# 'regulate' and 'optimize' modules.

<filter **>
	# Parses the JSON part of the TSV event returned from the 10x pipeline
	#
	# The reasons for this "two-step" move from TSV into JSON instead of directly parsing the result are:
	#
	# 1. We want to extract the tag immediately when reading back from 10x.
	#    Tag extraction happens as part of data returned from the exec_filter; see: 'tenx-exec-filter.conf'
	#
	# 2. The 'Yajl' library parsers JSON in exec_filter buffers data
	#    which may cause delays. See: https://docs.fluentd.org/output/exec_filter 
	#
	key_name json_data
	@type parser
	<parse>
		@type json
	</parse>
</filter>
