# Fluentd 'exec-filter' output configuration
#
# This configuration is used to add an 'exec-filter' plugin to a Fluentd
# pipeline that launches and writes events to a 10x sub-process.
#
# To learn more see: 'run/modules/forwarder/fluentd/readme.md'
#

# Settings up the 10x engine as an exec filter for fluentd to pass events into
#
@type exec_filter

# Respawn pipeline if it dies
#
child_respawn -1

command "#{ENV['TENX_BIN'] || '/opt/tenx-edge/bin/tenx'} run #{ENV['TENX_RUN_ARGS']}"

<inject>
	# Adds the event tag into the input for the 10x pipeline.
	# This is needed to allow restoring the original tag once the 10x
	# pipeline is done processing the event.
	#
	tag_key tenx_tag
</inject>
<format>
	# Formats the event as a JSON going into the 10x pipeline.
	#
	@type json
</format>
