# This Fluentd configuration is used internally by the 'regulate' and 'optimize' modules.
#
<match tenx-stdout>
	# Log 10x pipeline stdout messages to stdout
	#
	@type relabel
	@label @TENX-STDOUT
</match>
<match **>
	# Insert the resulting events back to the main Fluentd pipeline,
	# for processing according to the @TENX-PROCESSED label.
	#
	@type relabel
	@label @TENX-PROCESSED
</match>
