# A Fluent D exec-filter, used by the stdio-backed 'regulate' and 'optimize' pipelines
# used for emitting events from Fluent D into the 10x pipeline

<label @TENX>
	<match **>
		# Adds the base 'exec-filter' config to launch a 10x sub-process
		#
		@include tenx-exec-filter.conf
		
		# Adds the parse section for the exec filter
		#
		@include tenx-stdio-exec-filter-parse.conf

		# Pass all the events into a second phase of processing, which will properly
		# parse json_data, and will forward the events to their proper processing directives
		#
		@label @TENX-PHASE-2
	</match>
</label>
