# A Fluentd Unix source, used by the Unix domain socket 'regulate' and 'optimize' modules
# for reading events back into Fluentd

<source>
	# Reading events back from the 10x pipeline via the Fluentd 
	# 'forward' protocol over Unix domain socket.
	#
	@type unix

	# Address for the socket file, automatically picked up by the 10x process from here
	# to use as an output address (see '/run/modules/forwarder/fluentd/output/unix/stream.yaml')
	#
	path /tmp/tenx_fluentd.sock

	# Apply phase 2 label for additional processing and separation of events.
	#
	@label @TENX-PHASE-2
</source>
