# Parse and extract sections for 'exec-filter'
#
# only used in a 'regulate' / 'optimize' stdio-backed configuration as:
# 1. The 'report' configuration does not write back into the Fluentd pipeline.
# 2. Unix domain socket-backed 'regulate'/ 'optimize' configurations write  
#    into the FluentD pipeline using a Unix domain socket input.
#
<parse>
	# Parses the event returned from the 10x pipeline as a TSV.
	# We don't parse directly as JSON here because the  'exec_filter' uses the 'Yajl' parser library which
	# buffers data internally, which may cause delays.
	# See: 'https://docs.fluentd.org/output/exec_filter'
	#
	@type tsv
	keys tag, json_data
</parse>
<extract>
	# Sets the event tag based on the 'tag' field of the result TSV event.
	# This can either be the original tag set via the above '<inject>'
	# directive, or a new 10x tag for generated 10x events, such as
	# 'tenx-template' for the encoded event templates.
	#
	tag_key tag
</extract>
