# A Fluentd 'exec-filter' used by the unix-backed 10x 'regulate' and 'optimize' modules
# This configuration emits events from Fluentd into the 10x 'run' pipeline

<label @TENX>
	<match **>
		# Adds the base config for emitting events into the 10x pipeline
		#
		@include tenx-exec-filter.conf
		
		# This 10x pipeline configuration emits information
		# about the 10x pipeline initialization, useful for verifying the proper configuration
		<parse>
			@type none
		</parse>

		tag tenx-stdout

		@label @TENX-STDOUT
	</match>
</label>
<label @TENX-STDOUT>
	<match **>
		@type stdout
	</match>
</label>
